--- #################### 注册中心 + 配置中心相关配置 ####################
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      grace-destroy: false #是否优雅关闭数据源，默认为false，设置为true时，关闭数据源时如果数据源中还存在活跃连接，至多等待10s后强制关闭
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/dd
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://localhost:3306/dd
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: localhost # 地址
    port: 6379 # 端口
    database: 0 # 数据库索引
    password: 123456 # 密码，建议生产环境开启

  cloud:
    nacos:
      server-addr: localhost:8848 # Nacos 服务器地址
      username: nacos
      password: nacos
      discovery: # 【注册中心】配置项
        namespace: local # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
      config: # 【配置中心】配置项
        namespace: local # 命名空间。这里使用 dev 开发环境
        group: DEFAULT_GROUP # 使用的 Nacos 配置分组，默认为 DEFAULT_GROUP
        refresh-enabled: true  # 开启自动刷新

# 日志文件配置
logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: INFO